### ISSUE TITLE
Spark UI not working

### ISSUE THREAD

**Issue by jarutis** [andypetrella/spark-notebook#247] opened 2015-07-13 11:11 UTC
When I try to access Spark Application Master UI I get the following error:

```
HTTP ERROR 500

Problem accessing /jobs/. Reason:

    Server Error
Caused by:

java.lang.NullPointerException
	at org.spark-project.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.spark-project.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.spark-project.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.spark-project.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.spark-project.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.spark-project.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.spark-project.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.spark-project.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.spark-project.jetty.server.Server.handle(Server.java:370)
	at org.spark-project.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.spark-project.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.spark-project.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.spark-project.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.spark-project.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.spark-project.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.spark-project.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.spark-project.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.spark-project.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.spark-project.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

I'm running spark on yarn-client mode. For jobs submitted through spark-submit or spark-shell UI works fine.

**Comment by andypetrella** [comment] 2015-07-15 20:33
This is very weird, it's probably a missing conf parameter or whatever needed by the UI :-(.

Not gonna be easy to track or reproduce...

**Comment by lev112** [comment] 2015-07-17 08:27
I opened #258 with the same issue, and I have some more info there and a workaround

**Comment by andypetrella** [comment] 2015-07-17 09:53
@jarutis since #258 has been closed by #259, could give the UI a try using the master? :-D

**Comment by jarutis** [comment] 2015-07-17 11:01
Still the same

**Comment by andypetrella** [comment] 2015-07-17 11:18
with master, damned, do you still have the ClassNotFound and the NPE?

Could you also check the lib folder of your install to see if the missing/added jar is present?

**Comment by jarutis** [comment] 2015-07-17 11:37
It works now, maybe it also had something to do with my dependancies in the notebook which I tested. But now it works fine. I think we can close it now.

**Closed** 2015-07-17 11:38 UTC
