### ISSUE TITLE
Cannot read Parquet files

### ISSUE THREAD

**Issue by tfindlay-au** [andypetrella/spark-notebook#177] opened 2015-05-17 23:09 UTC
Building from "master" or "origin" with:
root@FFXDev01:~/spark-notebook# sbt -Dhadoop.version=2.4.0 -Djets3t.version=0.9.3 -Dscala.version=2.10.4 -Dmesos.version=0.22.1 -Dwith.hive=true -Dspark.version=1.3.1

Executing the following code:
import org.apache.spark.sql.SQLContext
val sqlContext = new SQLContext( sparkContext )
val newRows = sqlContext.load( "/home/ubuntu/data/smh/" )

....to read a parquet file generated via Spark 1.3.1 produces this result:
java.lang.NoSuchFieldError: NO_FILTER
	at org.apache.spark.sql.parquet.ParquetRelation2$MetadataCache$$anonfun$refresh$6.apply(newParquet.scala:299)
	at org.apache.spark.sql.parquet.ParquetRelation2$MetadataCache$$anonfun$refresh$6.apply(newParquet.scala:297)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:658)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:650)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:172)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by tfindlay-au** [comment] 2015-05-18 00:58
Tried rebuilding without Hive support like:
sbt -Dhadoop.version=2.4.0 -Djets3t.version=0.9.3 -Dscala.version=2.10.4 -Dmesos.version=0.22.1 -Dspark.version=1.3.1

Then executed the same code above and I got this output:
java.lang.NoClassDefFoundError: parquet/format/converter/ParquetMetadataConverter
	at org.apache.spark.sql.parquet.ParquetRelation2$MetadataCache$$anonfun$refresh$6.apply(newParquet.scala:299)
	at org.apache.spark.sql.parquet.ParquetRelation2$MetadataCache$$anonfun$refresh$6.apply(newParquet.scala:297)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:658)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:650)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:172)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
	at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:444)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:514)
	at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:492)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:64)
	at scala.collection.parallel.mutable.ParArray.map(ParArray.scala:589)
	at org.apache.spark.sql.parquet.ParquetRelation2$MetadataCache.refresh(newParquet.scala:297)
	at org.apache.spark.sql.parquet.ParquetRelation2.<init>(newParquet.scala:391)
	at org.apache.spark.sql.parquet.DefaultSource.createRelation(newParquet.scala:90)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:219)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:697)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:673)
	at org.apache.spark.sql.SQLContext.load(SQLContext.scala:662)

I tried importing a parquet JAR but same error:
:cp /home/ubuntu/parquet-hadoop-1.5.0.jar
import parquet.format.converter.ParquetMetadataConverter

**Comment by tfindlay-au** [comment] 2015-05-18 05:40
In anger, I hacked up ./project/Dependencies.scala

I removed:
,ExclusionRule("com.twitter", "parquet-column"), ExclusionRule("com.twitter", "parquet-hadoop")

From 2 lines
def sparkHive...
def sparkSQL...

Then did a clean, dist and it's now working! :)

This is probably not a good solution. I presume the exclusion rules were put in for a reason ?

**Comment by andypetrella** [comment] 2015-05-18 09:15
@tfindlay-au thanks to hack it around and nice catch!!
Actually, I added these exclude because their versions were conflicting sometimes with other libraries (adam mostly).
So I was wondering if it wouldn't be better for the user to add them manually.

The problem can also be that these two deps (sql and hive) could be excluded from the transitive deps and forcing the notebook to always requesting them (I need more thinking on that and see the impacts).

Something to try out is to declare them back in the notebook like this:
```
:dp org.apache.spark % spark-hive_2.10 % 1.3.1
org.apache.spark % spark-sql_2.10 %  1.3.1
```

If you have a notebook reproducing the problem in 0.5.0, I can test it out and let you know if you want?

**Comment by andypetrella** [comment] 2015-06-18 14:49
I think the `-Dwith.parquet` and `-Dwith.hive` is the best solution around so that the ops knows he wants such deps in the server too, and not only in the notebooks only.

So I'll close it until someone disagrees or faces problem :smile:

**Closed by andypetrella** 2015-06-18 14:49 UTC
Labels: bug
