### ISSUE TITLE
Kernel > Interrupt 404ing

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#338] opened 2015-10-09 22:38 UTC
![](http://cl.ly/image/2d3v2W1i0A0O/Screen%20Shot%202015-10-09%20at%206.36.55%20PM.png)

Seeing this in a notebook that is hanging; the spark job associated with my running cell failed, but the notebook hasn't noticed and I can't figure out how to resuscitate it:

![](http://cl.ly/image/3V2A3C2B0q2C/Screen%20Shot%202015-10-09%20at%206.38.09%20PM.png)

**Comment by andypetrella** [comment] 2015-10-12 16:02
@ryan-williams so, the problem is that the job is actually dead but the notebook is still running (the cell is blocked with a * ) ? Right?

In this case, you should be able to use the flame button, but I think we still need to harden this one too, it's in the same mood of the #270. I've limited bandwidth in October, but I think I will work on that one soon!

**Comment by andypetrella** [comment] 2015-10-26 01:13
fixed by https://github.com/andypetrella/spark-notebook/commit/07db1201edede491706c32329ef2151edd01a493

**Closed** 2015-10-26 01:13 UTC
