### ISSUE TITLE
Loading a gzip file with JSON inside is giving errors - Please help!

### ISSUE THREAD

**Issue by cagalli83** [andypetrella/spark-notebook#380] opened 2015-11-13 09:46 UTC
I tried loading a gzipped json file into a dataframe and spark-notebook is giving the error pasted below. I tried the same code in the spark scala shell and it's working fine. Am i missing something?

The directory tree looks like:
anonymous@ubuntu:~/TestFiles/raw/3.0$ tree
.
├── events-ac110b.1439499186791.gz
├── events-ac1111e.1439351901116.gz
├── events-ac1111e.1439351901123.gz
├── events-ac1111e.1439600006613.gz
├── events-ac111643.1438898329904.gz
├── events-ac111643.1438898329971.gz

Spark commands:
val filePath = "/home/TestFiles/raw/3.0/*"
val rawLogs = sqlContext.read.schema(schema).json(filePath)

Exception I'm getting:
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1057)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1038)
	at java.lang.reflect.Field.get(Field.java:379)
	at notebook.kernel.Repl.getModule$1(Repl.scala:203)
	at notebook.kernel.Repl.iws$1(Repl.scala:212)
	at notebook.kernel.Repl.liftedTree1$1(Repl.scala:219)
	at notebook.kernel.Repl.evaluate(Repl.scala:199)
	at notebook.client.ReplCalculator$$anonfun$15$$anon$1$$anonfun$29.apply(ReplCalculator.scala:376)
	at notebook.client.ReplCalculator$$anonfun$15$$anon$1$$anonfun$29.apply(ReplCalculator.scala:373)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NoSuchMethodException: org.apache.spark.io.SnappyCompressionCodec.<init>(org.apache.spark.SparkConf)
	at java.lang.Class.getConstructor0(Class.java:2892)
	at java.lang.Class.getConstructor(Class.java:1723)
	at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.scala:66)
	at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.scala:60)
	at org.apache.spark.broadcast.TorrentBroadcast.org$apache$spark$broadcast$TorrentBroadcast$$setConf(TorrentBroadcast.scala:73)
	at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:80)
	at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
	at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:63)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1327)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:96)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:58)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:396)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:926)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:924)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:930)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:930)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:933)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:933)
	at org.apache.spark.sql.DataFrame.rdd$lzycompute(DataFrame.scala:1486)
	at org.apache.spark.sql.DataFrame.rdd(DataFrame.scala:1483)
	at org.apache.spark.sql.DataFrame.mapPartitions(DataFrame.scala:1351)
	at org.apache.spark.sql.DataFrame.toJSON(DataFrame.scala:1534)
	at notebook.front.widgets.DataFrameView$class.notebook$front$widgets$DataFrameView$$json(DataFrame.scala:40)
	at notebook.front.widgets.DataFrameWidget.notebook$front$widgets$DataFrameView$$json$lzycompute(DataFrame.scala:64)
	at notebook.front.widgets.DataFrameWidget.notebook$front$widgets$DataFrameView$$json(DataFrame.scala:64)
	at notebook.front.widgets.DataFrameView$class.$init$(DataFrame.scala:41)
	at notebook.front.widgets.DataFrameWidget.<init>(DataFrame.scala:69)
	at notebook.front.ExtraLowPriorityRenderers$dataFrameAsTable$.render(renderer.scala:13)
	at notebook.front.ExtraLowPriorityRenderers$dataFrameAsTable$.render(renderer.scala:12)
	at notebook.front.Widget$.fromRenderer(Widget.scala:32)
	at $line21.$rendered$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<init>(<console>:63)
	at $line21.$rendered$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$.<clinit>(<console>)

**Comment by benqua** [comment] 2016-01-06 22:48
Same here while loading an uncompressed csv file with com.databricks.spark.csv on andypetrella/spark-notebook:0.6.2-scala-2.11.7-spark-1.5.2-hadoop-2.2.0 (docker).

**Comment by shadjiiski** [comment] 2016-01-07 15:37
@benqua I am successfully reading uncompressed CSVs on
`Build: |  buildTime-Mon Dec 07 14:34:13 EET 2015 | formattedShaVersion-0.6.2-SNAPSHOT-965aa22546c3514f9b5b5982d270c075f9c88c49 | sbtVersion-0.13.8 | scalaVersion-2.10.6 | sparkNotebookVersion-0.6.2-SNAPSHOT | hadoopVersion-2.6.0-cdh5.4.2 | jets3tVersion-0.7.1 | jlineDef-(org.scala-lang,2.10.6) | sparkVersion-1.6.0 | withHive-true | withParquet-true |.`

I have a cell that adds the dependency:
```
:dp
com.databricks %% spark-csv % 1.3.0
```
and then I use it like this:
```
val df = sqlContext.read
    .format("com.databricks.spark.csv")
    .option("header", "true")
    .option("inferSchema", "true")
    .load(LOOKUP_DATA_CSV)
```

The only limitation that I could not get over was the incorrect parsing of multiline values. I guess the library is designed to use `SparkContext.textFile()` which splits the file on every newline. Hope this helps you solve your issue.

**Comment by benqua** [comment] 2016-01-08 07:35
@shadjiiski Yes, it used to work for me too. It is just with the mentioned docker version that I hit this problem. 
In fact, reading the file seems to work, I think it is the rendering of the preview that fails.

**Comment by cagalli83** [comment] 2016-01-08 09:06
Meanwhile, i am still unable to load json. Does anyone have any tips on how to go about this?

**Comment by benqua** [comment] 2016-01-08 14:01
@andypetrella if you provide a hint I could try to work on a fix.

@cagalli83 does the load really fail? In my case, I get the message saying "Ooops, exception in the cell: " and there is no preview of the dataframe, but but data get loaded from the csv to the dataframe as expected.

**Comment by cagalli83** [comment] 2016-01-13 09:38
@benqua - you're right - it does say "Ooops, exception in the cell:" but no reason is given. However, when i tried to do rawLogs.show(), it gives me some data - which means that the data is loaded. Thanks for this!

**Comment by benqua** [comment] 2016-01-13 09:38
hmm, cannot reproduce any more with the exact same notebook and same spark-notebook version. Note sure what changed; maybe I had a conflicting com.databrick.csv version in my cache.

**Comment by benqua** [comment] 2016-01-16 13:42
Ok, I can confirm that dataframe preview works with (docker)  andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.4.0 but not with andypetrella/spark-notebook:0.6.2-scala-2.11.7-spark-1.5.2-hadoop-2.2.0 where it fails with "java.lang.NoSuchMethodException: org.apache.spark.io.SnappyCompressionCodec.(org.apache.spark.SparkConf)"

**Comment by andypetrella** [comment] 2016-01-16 13:59
sorry guys, we had hectic days. I'll take a look at that snappy thingy 

for the ooops crap, I think this is because the data has nulls out something, let me check too

will try asap...

**Comment by benqua** [comment] 2016-01-19 08:27
@andypetrella nice. 
Tell me if I can help. I mostly use spark-notebook for demonstration and these "oops" errors prevent me from using the latest versions. It is likely a regressions between 0.6.0 and 0.6.2.

**Comment by henrik-b** [comment] 2016-01-20 20:17
I also have the Ooops problem when displaying just normal DataFrames.

**Comment by andypetrella** [comment] 2016-01-20 21:02
@benqua @henrik-b 
Would you guyz check if you have null values or NA maybe?
If so, could you extract a smallish sample with them so I can try.
I'll try to create examples with this to see if the problem comes from ther.

**Comment by andypetrella** [comment] 2016-01-21 15:43
So... it's "funny" thing:
if you try
```scala
val df = ??? // whatever here that is throwing an exception
df // boom
```
You can execute it several times, you'll keep having the exception.

Now, change this cell into
```scala
val df = ??? // whatever here that is throwing an exception
//df
new DataFrameWidget(df, 25, "consoleDir")
```
execute it, it works.
Now change it back to the original:
```scala
val df = ??? // whatever here that is throwing an exception
df // WORKS !!!!
```

And it's gonna work, all the time... pretty weirdo!

So there is a workaround that will work, but not great, I'll try to nail down to the real issue...
Meanwhile, I hope this will be good enough :-S.

**Comment by henrik-b** [comment] 2016-01-22 11:14
Hi Andy,
the Problem eben occurs for queries like select count (*) from table.I see no relation to null or n/a.
Henrik

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Andy Petrella <notifications@github.com> 
Datum: 20.01.2016  22:02  (GMT+01:00) 
An: andypetrella/spark-notebook <spark-notebook@noreply.github.com> 
Cc: Henrik Behrens <HenrikBehrens@gmx.net> 
Betreff: Re: [spark-notebook] Loading a gzip file with JSON inside is giving
  errors - Please help! (#380) 

@benqua @henrik-b 

Would you guyz check if you have null values or NA maybe?

If so, could you extract a smallish sample with them so I can try.

I'll try to create examples with this to see if the problem comes from ther.

**Comment by andypetrella** [comment] 2016-01-22 11:49
@henrik-b you're right, this comment is obsolete... I'll delete it (sorry)

However check this one: https://github.com/andypetrella/spark-notebook/issues/380#issuecomment-173610978

**Comment by deanwampler** [comment] 2016-02-11 23:28
The [#380 (comment)](https://github.com/andypetrella/spark-notebook/issues/380#issuecomment-173610978) isn't working for me. What I did just notice is that a cell that ends with `myDF.cache` will successfully render `myDF` with the widget and not throw the exception. Otherwise, I've switched to using `.show(n)` for the time being.

**Comment by deanwampler** [comment] 2016-02-11 23:29
Crap. Strike that. I just saw the exception thrown by a `myDF.cache` statement.

**Comment by andypetrella** [comment] 2016-02-11 23:39
So ;-) is the workaround working for you? or is there a problem still?

cache indeed can make it failing since it return a DF too (even if has side effect :cry:)

**Comment by chernetsov** [comment] 2016-03-08 16:49
got the same issue with the build spark-notebook-0.6.2-scala-2.11.7-spark-1.6.0-hadoop-2.4.0

**Comment by chiangqiqi** [comment] 2016-03-10 02:23
got the same issue with the build spark-notebook-0.6.2-scala-2.11.7-spark-1.6.0-hadoop-2.4.0, 
It works well if I use 
`df.take(n)`

**Comment by vidma** [comment] 2016-03-22 12:02
looks to me like widgets fuckup with `scala-2.11`  (we've seen a similar error in 2.11, then any sql dataframe is automatically rendered - last value in the cell).

so try scala 2.10 if you can.

might be related  to #620

**Comment by arjenpdevries** [comment] 2016-05-20 11:28
Dear all, has this been resolved?

I found that I get the same Oops whenever I read the sample people.json file from the documentation, whether I read it as json or even as text:
```
val t = sqlContext.read.text(fp)
```

Any new insight in this issue since March?

**Comment by arjenpdevries** [comment] 2016-05-20 14:18
After some trial and error, I manage to switch the compression algorithm from snappy to lz4, by creating a new context after modifying the compression codec choice:
```
val newConf = sc.getConf.set("spark.io.compression.codec","lz4")
```

The result is the same, only changing the missing method that is reported as follows:
```
Caused by: java.lang.NoSuchMethodException: org.apache.spark.io.LZ4CompressionCodec.<init>(org.apache.spark.SparkConf)
```

So the cause seems different from either file input/output and the choice of compression used.

**Comment by andypetrella** [comment] 2016-05-23 22:41
arf, which versions are you using actually?

**Comment by arjenpdevries** [comment] 2016-05-24 08:02
I use:
andypetrella/spark-notebook:0.6.2-scala-2.11.7-spark-1.6.0-hadoop-2.7.1-with-hive-with-parquet

Judging from the comments, it seems related to scala 2.11.

**Comment by arjenpdevries** [comment] 2016-06-03 10:39
Upgrading the notebook to 0.6.3 resolves this problem (and is recommended anyways - prettier UI),
so the issue can be closed.

/cc @andypetrella

**Comment by andypetrella** [comment] 2016-06-03 15:42
oki cool then!!! 
thanks  @arjenpdevries , I'll close it and mention it a bit more clearly

**Closed by andypetrella** 2016-06-03 15:42 UTC
Labels: bug

**Comment by Physiker99** [comment] 2017-01-24 16:07
There is no binary package for 0.6.3 . The latest release is 0.6.2.

**Comment by andypetrella** [comment] 2017-01-24 18:39
Hehe well I'd say 0.7.0 is the one to use otherwise the master snapshot
